baseURL = 'http://example.org/'
languageCode = 'en-us'
title = 'Gateway Small Bay Industrial - Comming Soon!'

theme = 'bootstrap_bp_hugo'

DefaultContentLanguage = "en"
enableInlineShortcodes = true
# prevent build failures when using Hugo's Instagram shortcode due to deprecated Instagram API.
# See https://github.com/gohugoio/hugo/issues/7228#issuecomment-714490456
ignoreErrors = ["error-remote-getjson"]

footnoteReturnLinkContents = "^"

# Theme specific examples
author = "Justin B Kay"
copyright = "OlympusPM"
# googleAnalytics = "UA-123-45"
enableRobotsTXT = true
pygmentsCodeFences = true
canonifyurls = true
paginate = 6

[sitemap]
changefreq = "weekly"
priority = 0.5

[permalinks]
posts = "/:year/:month/:slug/"
post = "/:year/:month/:slug/"
pages = "/:slug/"
page = "/:slug/"

[Author]
name = "Justin B. Kay"

[params]
description = "For rent `industrial space`, `small bay industrial space`, `warehouse`, `small warehouse` in Mesa, Gilbert or Queen Creek Arizona"
# images = ["gateway_industrial_render.jpg"]
# showPostSummary = true
# startPageColumns = true
# showListsGrouped = true
alwaysExpandMenu = true
customDateFormat = "02/01/2006"
# hideReadingTime = true
themeColor = "light" # dark, light, blue, do not set for bootstrap default
# js=["/js/test_site.js"]
# css=["/css/test_site.css"]
# csscdn=["https://fonts.googleapis.com/css?family=Concert+One|Roboto&display=swap"]


#[languages]
#  [languages.en]
#    languageName = "English"
#    title = "My blog"
#    weight = 1
#    [languages.en.params]
#  [languages.de]
#    languageName = "Deutsch"
#    title = "Mein Blog"
#    weight = 2
#    [languages.de.params]


# Sets Social Media icons to appear and link to your account. Value should be your
# username unless otherwise noted.
# Code from https://themes.gohugo.io/future-imperfect/ theme
[social]
# Coding Communities
github = ""
gitlab = ""
stackoverflow = "" # User Number
bitbucket = ""
jsfiddle = ""
codepen = ""
# Visual Art Communities
deviantart = ""
flickr = ""
behance = ""
dribbble = ""
# Publishing Communities
wordpress = ""
medium = ""
# Professional/Business Oriented Communities
linkedin = "traviskay"
linkedin_company = "olympus-construction-management"
foursquare = ""
xing = ""
slideshare = ""
# Social Networks
facebook = "travis.kay.9"
googleplus = ""
reddit = ""
quora = ""
youtube = ""
vimeo = ""
whatsapp = ""             # WhatsApp Number
instagram = ""
tumblr = ""
twitter = ""
skype = ""
snapchat = ""
pinterest = ""
telegram = ""
discord = ""              # invite link
# Email
email = ""


[menu]

# [[menu.main]]
#   identifier = "about"
#   name = "About"
#   url = "/about/"
#   weight = 10
#   pre = "<i class='fas fa-heart'></i>"

# [[menu.footer]]
#   identifier = "about"
#   name = "About"
#   url = "/about/"
#   weight = 10
#   pre = "<i class='fas fa-address-card'></i>"

# [[menu.footer]]
#   identifier = "categories"
#   name = "Categories"
#   url = "/categories/"
#   weight = 20
#   pre = "<i class='fas fa-folder'></i>"

[[menu.footer]]
identifier = "tags"
name = "Tags"
url = "/tags/"
weight = 30
pre = "<i class='fas fa-tags'></i>"


[taxonomies]
# category = "categories"
tag = "tags"
# series = "series"

[privacy]

[privacy.vimeo]
disabled = false
simple = true

[privacy.twitter]
disabled = false
enableDNT = true
simple = true

[privacy.instagram]
disabled = false
simple = true

[privacy.youtube]
disabled = false
privacyEnhanced = true

[services]

[services.instagram]
disableInlineCSS = true

[services.twitter]
disableInlineCSS = true
